# ---------------------------------------------------------------------------------------------------------------------
# REQUIRED PARAMETERS
# ---------------------------------------------------------------------------------------------------------------------
variable "location" {
  default     = ""
  description = "Azure location in condensed form, e.g. 'useast2', 'uscentral'"
}

variable "boundary" {
  description = "The boundary of subnet/NSG group. Allowed values: 'Internal', 'External'"
}

variable "solution" {
  description = "Solution or application name"
}

variable "environment" {
  description = "Application environment, allowed values: 'Development', 'Production', 'Quality', 'Test', 'Staging'"
}

# ---------------------------------------------------------------------------------------------------------------------
# OPTIONAL PARAMETERS
# ---------------------------------------------------------------------------------------------------------------------
variable "attributes" {
  type        = list(string)
  default     = []
  description = "Additional attributes, for differentiation (e.g. `1`)"
}

variable "enabled" {
  type        = bool
  default     = true
  description = "Set to false to prevent the module from creating any resources"
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Additional tags (e.g. `{'BusinessUnit','XYZ'}`"
}

variable "delimiter" {
  type        = string
  default     = null
  description = "Delimiter to be used between elements of the name"
}

variable "standardize" {
  type        = bool
  default     = true
  description = "Set to false to leave the the name elements as they are passed in"
}

variable "include_environment" {
  type        = bool
  default     = true
  description = "Include environment as part of the resource name"
}

variable "use_short_environment" {
  type        = bool
  default     = false
  description = "When mapping environment names, use the shortened environment name"
}

variable "include_generated_tags" {
  type        = bool
  default     = false
  description = "Allows additional tags generated by the module parameters"
}

variable "regex_replace_chars" {
  type        = string
  default     = "/[^a-zA-Z0-9-]/"
  description = "Regex to replace chars with empty string for the name elements. By default only hyphens, letters and digits are allowed, all other chars are removed"
}

variable "environment_instance" {
  type        = number
  default     = 0
  description = "Number indicating instance of environment"
}

